### ISSUE TITLE
use of unstable library feature 'stdsimd'

### ISSUE THREAD

**Issue by ous51m1** [BLAKE3-team/BLAKE3#57]
how can i move on with my life 

```
error[E0658]: use of unstable library feature 'stdsimd'
   --> /home/oussama/.cargo/registry/src/github.com-1ecc6299db9ec823/blake3-0.1.4/src/platform.rs:266:12
    |
266 |         if is_x86_feature_detected!("avx512f") && is_x86_feature_detected!("avx512vl") {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/27731
    = help: add `#![feature(stdsimd)]` to the crate attributes to enable
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `blake3`.
```

**Comment by oconnor663** [comment]
This is a bug in nightly. See https://github.com/BLAKE3-team/BLAKE3/issues/56 and https://github.com/rust-lang/rust/issues/68905.

Until this is fixed, if you have to use nightly, you will need to use a nightly version from before this but was introduced. I don't know exactly when that was yet, but probably a couple weeks ago would be fine?

**Comment by ous51m1** [comment]
thanks @oconnor663 i switched to `stable` and my problem is now resolved :)

**Comment by oconnor663** [comment]
It looks like nightly-2020-02-06 is the first compiler version with this issue. Anything prior to that should work.

**Comment by oconnor663** [comment]
I've released version 0.1.5, which is a backport of af2e791602ca59a5258b6d0f8f49845213a916a2. This should unbreak nightly builds of the `blake3` crate with the default feature set. Only callers who enable the `c_avx512` feature (which includes `b3sum`) will remain broken on nightly.

**Comment by zaynetro** [comment]
Can confirm that stable compiler can compile `b3sum`.

```
$ rustc --version
rustc 1.41.1 (f3e1a954d 2020-02-24)
```

**Comment by oconnor663** [comment]
This is fixed as of `rustc 1.44.0-nightly (38114ff16 2020-03-21)` and `rustc 1.43.0-beta.596 (1eaaee956 2020-03-22)`.

**Comment by OfekShochat** [comment]
I get this problem with the fully updated nightly stable and beta now (1.54.0-nightly (5dc8789e3 2021-05-21), rustc 1.53.0-beta.2 (4bac69dd2 2021-05-07), rustc 1.51.0 (2fd73fabe 2021-03-23))

**Comment by oconnor663** [comment]
@OfekShochat are you saying that `b3sum` fails to build for you on all three toolchains? With an error message about `stdsimd`? I need you to give a lot more detail about what platform you're on and what commands you're running to have any chance of understanding the problem. Could you please file a new issue, with as much detail as possible?

**Comment by jianshu93** [comment]
I still have this error on 1.57. it is really strange. Any idea how to fix?

Jianshu

**Comment by ChaseLewis** [comment]
Yeah i'm getting this with avx instructions on nightly like _mm_maskz_div_ps in 1.69.0 - nightly
